# Generated by Django 5.1.2 on 2024-11-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_remove_client_created_at_remove_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
